program M2Server;

uses
  Forms,
  Windows,
  Graphics,
  svMain in 'svMain.pas' {FrmMain},
  LocalDB in 'LocalDB.pas' {FrmDB},
  InterServerMsg in 'InterServerMsg.pas' {FrmSrvMsg},
  InterMsgClient in 'InterMsgClient.pas' {FrmMsgClient},
  IdSrvClient in 'IdSrvClient.pas' {FrmIDSoc},
  FSrvValue in 'FSrvValue.pas' {FrmServerValue},
  UsrEngn in 'UsrEngn.pas',
  ObjNpc in 'ObjNpc.pas',
  ObjMon2 in 'ObjMon2.pas',
  ObjMon in 'ObjMon.pas',
  ObjGuard in 'ObjGuard.pas',
  ObjBase in 'ObjBase.pas',
  ObjAxeMon in 'ObjAxeMon.pas',
  NoticeM in 'NoticeM.pas',
  Mission in 'Mission.pas',
  Magic in 'Magic.pas',
  M2Share in 'M2Share.pas',
  ItmUnit in 'ItmUnit.pas',
  Guild in 'Guild.pas',
  FrnEngn in 'FrnEngn.pas',
  Event in 'Event.pas',
  Envir in 'Envir.pas',
  Castle in 'Castle.pas',
  RunDB in 'RunDB.pas',
  RunSock in 'RunSock.pas',
  Grobal2 in '..\Common\Grobal2.pas',
  HUtil32 in '..\Common\HUtil32.pas',
  GeneralConfig in 'GeneralConfig.pas' {frmGeneralConfig},
  GameConfig in 'GameConfig.pas' {frmGameConfig},
  FunctionConfig in 'FunctionConfig.pas' {frmFunctionConfig},
  ObjRobot in 'ObjRobot.pas',
  ViewSession in 'ViewSession.pas' {frmViewSession},
  ViewOnlineHuman in 'ViewOnlineHuman.pas' {frmViewOnlineHuman},
  ViewLevel in 'ViewLevel.pas' {frmViewLevel},
  ViewList in 'ViewList.pas' {frmViewList},
  OnlineMsg in 'OnlineMsg.pas' {frmOnlineMsg},
  HumanInfo in 'HumanInfo.pas' {frmHumanInfo},
  ViewKernelInfo in 'ViewKernelInfo.pas' {frmViewKernelInfo},
  ConfigMerchant in 'ConfigMerchant.pas' {frmConfigMerchant},
  ItemSet in 'ItemSet.pas' {frmItemSet},
  ConfigMonGen in 'ConfigMonGen.pas' {frmConfigMonGen},
  SDK in '..\SDK\SDK.pas',
  AES in '..\SDK\AES.pas',
  ElAES in '..\SDK\ElAES.pas',
  EncryptUnit in '..\Common\EncryptUnit.pas',
  GameCommand in 'GameCommand.pas' {frmGameCmd},
  MonsterConfig in 'MonsterConfig.pas' {frmMonsterConfig},
  UnitManage in 'UnitManage.pas',
  ActionSpeedConfig in 'ActionSpeedConfig.pas' {frmActionSpeed},
  EDcode in 'EDcode.pas',
  CastleManage in 'CastleManage.pas' {frmCastleManage},
  MD5Unit in 'MD5Unit.pas',
  MudUtil in '..\Common\MudUtil.pas',
  ObjMon3 in 'ObjMon3.pas',
  PlugShare in 'PlugAPI\PlugShare.pas',
  Shopping in 'Shopping.pas',
  FrmPlug in 'PlugAPI\FrmPlug.pas' {FormPlug},
  EngineType in '..\PlugInCommon\EngineType.pas',
  ViewList2 in 'ViewList2.pas' {FormList2},
  AttackWar in 'AttackWar.pas' {FormAttack},
  CenterShare in '..\Common\CenterShare.pas',
  ObjClone in 'ObjClone.pas',
  FrmAbout in 'FrmAbout.pas' {ABoutForm},
  FrmTaxis in 'FrmTaxis.pas' {FormTaxis},
  InfinityStorage in 'InfinityStorage.pas',
  ObjMon4 in 'ObjMon4.pas',
  FrmGuild in 'FrmGuild.pas' {FormGuild},
  M2Plug in 'M2Plug.pas',
  PlugApi in 'PlugAPI\PlugApi.pas',
  UserEngineApi in 'PlugAPI\UserEngineApi.pas',
  TListApi in 'PlugAPI\TListApi.pas',
  TStringListApi in 'PlugAPI\TStringListApi.pas',
  TBaseObjectApi in 'PlugAPI\TBaseObjectApi.pas',
  PlugFun in 'PlugAPI\PlugFun.pas',
  TPlayObjectApi in 'PlugAPI\TPlayObjectApi.pas',
  TNormNpcApi in 'PlugAPI\TNormNpcApi.pas',
  TEnvirnomentApi in 'PlugAPI\TEnvirnomentApi.pas',
  TMagicManagerApi in 'PlugAPI\TMagicManagerApi.pas',
  TItemApi in 'PlugAPI\TItemApi.pas',
  FindMapPath in 'FindMapPath.pas',
  GloblVal in 'GloblVal.pas' {FormGloblVal},
  PlacingItem in 'PlacingItem.pas';

{$R *.res}

exports
  TMemoryManager_Get,TMemoryManager_AllocMemCount,TMemoryManager_AllocMemSize,

  TList_Create,TList_Free,TList_Count,TList_Add,TList_Insert,TList_Get,
  TList_Delete,TList_Clear,TList_Exchange,TList_Put,

  TStringList_Create,TStringList_Free,TStringList_Count,TStringList_Add,
  TStringList_AddObject,TStringList_Insert,TStringList_Get,TStringList_GetObject,
  TStringList_Put,TStringList_PutObject,TStringList_Delete,TStringList_Clear,
  TStringList_Exchange,TStringList_LoadFormFile,TStringList_SaveToFile,
  
  MainOutMessageAPI,AddGameDataLogAPI,TConfig_sEnvirDir,Config_sUserDataDir,
  GetGameGoldName,GetSellOffGoldTaxRate,GetSellOffGameGoldTaxRate,GetLevelItemRate,
  GetLevelItemGoldCount,GetLevelItemGameGoldCount,GetLevelItemGameCount,SetDemoNotice,

  EDcode_Decode6BitBuf,EDcode_Encode6BitBuf,EDcode_SetDecode,EDcode_SetEncode,
  EDcode_SetScript1,EDcode_SetScript2,

  TBaseObject_Create,TBaseObject_Free,TBaseObject_sMapFileName,TBaseObject_sMapName,
  TBaseObject_sMapNameA,TBaseObject_sCharName,TBaseObject_sCharNameA,TBaseObject_nCurrX,
  TBaseObject_nCurrY,TBaseObject_btDirection,TBaseObject_btGender,TBaseObject_btHair,
  TBaseObject_btJob,TBaseObject_nGold,TBaseObject_Ability,TBaseObject_WAbility,
  TBaseObject_nCharStatus,TBaseObject_sHomeMap,TBaseObject_nHomeX,TBaseObject_nHomeY,
  TBaseObject_boOnHorse,TBaseObject_btHorseType,TBaseObject_btDressEffType,
  TBaseObject_nPkPoint,TBaseObject_boAllowGroup,TBaseObject_boAllowGuild,
  TBaseObject_nFightZoneDieCount,TBaseObject_nBonusPoint,TBaseObject_nHungerStatus,
  TBaseObject_boAllowGuildReCall,TBaseObject_duBodyLuck,TBaseObject_nBodyLuckLevel,
  TBaseObject_wGroupRcallTime,TBaseObject_boAllowGroupReCall,TBaseObject_nCharStatusEx,
  TBaseObject_dwFightExp,TBaseObject_nViewRange,TBaseObject_wAppr,
  TBaseObject_btRaceServer,TBaseObject_btRaceImg,TBaseObject_btHitPoint,
  TBaseObject_nHitPlus,TBaseObject_nHitDouble,TBaseObject_boRecallSuite,
  TBaseObject_nHealthRecover,TBaseObject_nSpellRecover,TBaseObject_btAntiPoison,
  TBaseObject_nPoisonRecover,TBaseObject_nAntiMagic,TBaseObject_nLuck,
  TBaseObject_nPerHealth,TBaseObject_nPerHealing,TBaseObject_nPerSpell,
  TBaseObject_btGreenPoisoningPoint,TBaseObject_nGoldMax,TBaseObject_btSpeedPoint,
  TBaseObject_btPermission,TBaseObject_nHitSpeed,TBaseObject_TargetCret,TBaseObject_LastHiter,
  TBaseObject_ExpHiter,TBaseObject_btLifeAttrib,TBaseObject_GroupOwner,
  TBaseObject_GroupMembersList,TBaseObject_boHearWhisper,TBaseObject_boBanShout,
  TBaseObject_boBanGuildChat,TBaseObject_boAllowDeal,TBaseObject_Master,
  TBaseObject_btAttatckMode,TBaseObject_nNameColor,TBaseObject_nLight,
  TBaseObject_ItemList,TBaseObject_MagicList,TBaseObject_MyGuild,
  TBaseObject_UseItems,TBaseObject_btMonsterWeapon,TBaseObject_PEnvir,
  TBaseObject_boGhost,TBaseObject_boDeath,TBaseObject_DeleteBagItem,
  TBaseObject_AddCustomData,TBaseObject_GetCustomData,TBaseObject_SendMsg,
  TBaseObject_SendRefMsg,TBaseObject_SysMsg,TBaseObject_GetFrontPosition,
  TBaseObject_GetRecallXY,TBaseObject_SpaceMove,TBaseObject_FeatureChanged,
  TBaseObject_StatusChanged,TBaseObject_GetFeatureToLong,TBaseObject_GetFeature,
  TBaseObject_GetCharColor,TBaseObject_GetNamecolor,TBaseObject_GoldChanged,
  TBaseObject_GameGoldChanged,TBaseObject_MagCanHitTarget,TBaseObject_IsProtectTarget,
  TBaseObject_IsAttackTarget,TBaseObject_IsProperTarget,TBaseObject_IsProperFriend,
  TBaseObject_TrainSkillPoint,TBaseObject_GetAttackPower,TBaseObject_MakeSlave,
  TBaseObject_MakeGhost,TBaseObject_RefNameColor,TBaseObject_AddItemToBag,
  TBaseObject_AddItemToStorage,TBaseObject_ClearBagItem,TBaseObject_ClearStorageItem,
  TBaseObject_SetHookGetFeature,TBaseObject_SetHookEnterAnotherMap,
  TBaseObject_SetHookObjectDie,TBaseObject_SetHookChangeCurrMap,TBaseObject_boHero,

  TPlayObject_nSoftVersionDate,TPlayObject_nSoftVersionDateEx,TPlayObject_dLogonTime,
  TPlayObject_dwLogonTick,TPlayObject_nMemberType,TPlayObject_nMemberLevel,
  TPlayObject_nGameGold,TPlayObject_nGamePoint,TPlayObject_nPayMentPoint,
  TPlayObject_dwClientTick,
  TPlayObject_Create,TPlayObject_Free,TPlayObject_SendSocket,TPlayObject_SendDefMessage,
  TPlayObject_SendAddItem,TPlayObject_SendDelItem,TPlayObject_TargetInNearXY,
  TPlayObject_SetHookCreate,TPlayObject_GetHookCreate,TPlayObject_SetHookDestroy,
  TPlayObject_GetHookDestroy,TPlayObject_SetHookUserLogin1,TPlayObject_SetHookUserLogin2,
  TPlayObject_SetHookUserLogin3,TPlayObject_SetHookUserLogin4,TPlayObject_SetHookUserCmd,
  TPlayObject_GetHookUserCmd,TPlayObject_SetHookPlayOperateMessage,
  TPlayObject_GetHookPlayOperateMessage,TPlayObject_SetHookClientQueryBagItems,
  TPlayObject_SetHookClientQueryUserState,TPlayObject_SetHookSendActionGood,
  TPlayObject_SetHookSendActionFail,TPlayObject_SetHookSendWalkMsg,
  TPlayObject_SetHookSendHorseRunMsg,TPlayObject_SetHookSendRunMsg,
  TPlayObject_SetHookSendDeathMsg,TPlayObject_SetHookSendSkeletonMsg,
  TPlayObject_SetHookSendAliveMsg,TPlayObject_SetHookSendSpaceMoveMsg,
  TPlayObject_SetHookSendChangeFaceMsg,TPlayObject_SetHookSendUseitemsMsg,
  TPlayObject_SetHookSendUserLevelUpMsg,TPlayObject_SetHookSendUserAbilieyMsg,
  TPlayObject_SetHookSendUserStatusMsg,TPlayObject_SetHookSendUserStruckMsg,
  TPlayObject_SetHookSendUseMagicMsg,TPlayObject_SetHookSendSocket,
  TPlayObject_SetHookSendGoodsList,TPlayObject_SetCheckClientDropItem,
  TPlayObject_SetCheckClientDealItem,TPlayObject_SetCheckClientStorageItem,
  TPlayObject_SetCheckClientRepairItem,TPlayObject_SetHookCheckUserItems,
  TPlayObject_SetHookRun,TPlayObject_SetHookFilterMsg,TPlayObject_CheckPlaySideNpc,

  TNormNpc_sFilePath,TNormNpc_sPath,TNormNpc_GetLineVariableText,
  TNormNpc_SetScriptActionCmd,TNormNpc_GetScriptActionCmd,
  TNormNpc_SetScriptConditionCmd,TNormNpc_GetScriptConditionCmd,
  TNormNpc_GetManageNpc,TNormNpc_GetFunctionNpc,TNormNpc_GotoLable,
  TNormNpc_SetScriptAction,TNormNpc_GetScriptAction,
  TNormNpc_SetScriptCondition,TNormNpc_GetScriptCondition,
  TMerchant_GoodsList,TMerchant_GetItemPrice,TMerchant_GetUserPrice,
  TMerchant_GetUserItemPrice,TMerchant_SetHookClientGetDetailGoodsList,

  TMapManager_FindMap,TEnvirnoment_GetRangeBaseObject,TEnvirnoment_boCANRIDE,
  TEnvirnoment_boCANBAT,

  TUserEngine_Create,TUserEngine_Free,TUserEngine_GetUserEngine,
  TUserEngine_GetPlayObject,TUserEngine_GetLoadPlayList,TUserEngine_GetPlayObjectList,
  TUserEngine_GetLoadPlayCount,TUserEngine_GetPlayObjectCount,
  TUserEngine_GetStdItemByName,TUserEngine_GetStdItemByIndex,TUserEngine_CopyToUserItemFromName,
  TUserEngine_SetHookRun,TUserEngine_GetHookRun,TUserEngine_SetHookClientUserMessage,
  TUserEngine_GetClientItem,

  TMagicManager_GetMagicManager,TMagicManager_DoSpell,TMagicManager_MPow,
  TMagicManager_GetPower,TMagicManager_GetPower13,TMagicManager_GetRPow,
  TMagicManager_IsWarrSkill,TMagicManager_MagBigHealing,
  TMagicManager_MagPushArround,TMagicManager_MagPushArroundTaos,
  TMagicManager_MagTurnUndead,TMagicManager_MagMakeHolyCurtain,
  TMagicManager_MagMakeGroupTransparent,TMagicManager_MagTamming,
  TMagicManager_MagSaceMove,TMagicManager_MagMakeFireCross,
  TMagicManager_MagBigExplosion,TMagicManager_MagElecBlizzard,
  TMagicManager_MabMabe,TMagicManager_MagMakeSlave,TMagicManager_MagMakeSinSuSlave,
  TMagicManager_MagWindTebo,TMagicManager_MagGroupLightening,
  TMagicManager_MagGroupAmyounsul,TMagicManager_MagGroupDeDing,
  TMagicManager_MagGroupMb,TMagicManager_MagHbFireBall,
  TMagicManager_MagLightening,TMagicManager_SetHookDoSpell,TMerchant_boSellOff,

  TItemUnit_GetItemAddValue,TItemUnit_GetItem,TItemUnit_nStdMode,
  TItemUnit_nSellOff,TItemUnit_nNeedIdentify,TItemUnit_sItemName,TItemUnit_nLevelItem,
  TItemUnit_GetStandardItem,TItemUnit_nItemType,

  GetGameLogGold,GetGameLogGameGold,GetGameLogGamePoint,

  TGuild_RankList;

begin
  //g_Config.nM2Crc:=CalcFileCRC(Application.ExeName);
  Application.Initialize;
  Application.HintPause:=100;
  Application.HintShortPause:=100;
  Application.HintHidePause:=5000;

  Application.CreateForm(TFrmMain, FrmMain);
  Application.CreateForm(TFrmSrvMsg, FrmSrvMsg);
  Application.CreateForm(TFrmMsgClient, FrmMsgClient);
  Application.CreateForm(TFrmIDSoc, FrmIDSoc);
  Application.Run;
end.
